using UnityEngine;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine.UIElements;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Game.Inventory;
using Game.Combat;

namespace Game.Editor
{
    public class WeaponCreatorWindow : EditorWindow
    {
        // Tool-managed inputs (not SerializedObject-backed).
        private TextField _weaponNameField;
        private ObjectField _baseModelField;
        private DropdownField _weaponTypeField;

        // Dynamic SO inspector.
        private VisualElement _fieldsContainer;
        private ItemSO _workingInstance;       // Live, un-persisted draft of the selected weapon type.
        private SerializedObject _serializedObject;

        private List<System.Type> _weaponTypes;

        // Fields the tool generates/derives itself, so they are hidden from the dynamic inspector.
        private static readonly HashSet<string> ExcludedProperties = new()
        {
            "m_Script",
            "itemName",          // driven by the Weapon Name field
            "icon",              // generated by ItemIconGenerator
            "worldItemPrefab",   // generated below
            "equipVisualPrefab", // generated below
        };

        [MenuItem("Tools/Items/Weapon Creator")]
        public static void ShowWindow()
        {
            WeaponCreatorWindow wnd = GetWindow<WeaponCreatorWindow>();
            wnd.titleContent = new GUIContent("Weapon Creator");
            wnd.minSize = new Vector2(350, 450);
        }

        public void CreateGUI()
        {
            VisualElement root = rootVisualElement;

            root.style.paddingLeft = 10;
            root.style.paddingRight = 10;
            root.style.paddingTop = 10;
            root.style.paddingBottom = 10;

            Label title = new Label("Create New Weapon");
            title.style.fontSize = 20;
            title.style.unityFontStyleAndWeight = FontStyle.Bold;
            title.style.marginBottom = 10;
            root.Add(title);

            _weaponTypes = GetWeaponTypes();

            if (_weaponTypes.Count == 0)
            {
                root.Add(new HelpBox(
                    "No concrete WeaponSO subclasses found. Create a class deriving from WeaponSO (e.g. SwordSO) first.",
                    HelpBoxMessageType.Warning));
                return;
            }

            _weaponNameField = new TextField("Weapon Name");
            root.Add(_weaponNameField);

            List<string> typeNames = _weaponTypes.Select(t => t.Name).ToList();
            _weaponTypeField = new DropdownField("Weapon Type", typeNames, 0);
            _weaponTypeField.RegisterValueChangedCallback(_ => RebuildFields());
            root.Add(_weaponTypeField);

            _baseModelField = new ObjectField("Base Model (Prefab/Mesh)") { objectType = typeof(GameObject) };
            root.Add(_baseModelField);

            Label fieldsHeader = new Label("Item Properties");
            fieldsHeader.style.unityFontStyleAndWeight = FontStyle.Bold;
            fieldsHeader.style.marginTop = 10;
            fieldsHeader.style.marginBottom = 4;
            root.Add(fieldsHeader);

            _fieldsContainer = new VisualElement();
            root.Add(_fieldsContainer);

            VisualElement spacer = new VisualElement();
            spacer.style.height = 20;
            root.Add(spacer);

            Button createButton = new Button(OnCreateClicked) { text = "Create Weapon Assets" };
            createButton.style.height = 30;
            createButton.style.backgroundColor = new Color(0.2f, 0.4f, 0.2f);
            createButton.style.color = Color.white;
            root.Add(createButton);

            RebuildFields();
        }

        private void OnDisable()
        {
            // Draft instances that were never saved as assets must be destroyed to avoid leaking SOs.
            DestroyWorkingInstanceIfUnsaved();
        }

        private List<System.Type> GetWeaponTypes()
        {
            // TypeCache is Editor-only, fast, and robust against ReflectionTypeLoadException.
            return TypeCache.GetTypesDerivedFrom<WeaponSO>()
                .Where(t => !t.IsAbstract)
                .OrderBy(t => t.Name)
                .ToList();
        }

        // Rebuilds the dynamic SerializedObject inspector for the currently selected weapon type.
        private void RebuildFields()
        {
            DestroyWorkingInstanceIfUnsaved();

            System.Type selectedType = GetSelectedType();
            if (selectedType == null)
                return;

            _workingInstance = ScriptableObject.CreateInstance(selectedType) as ItemSO;
            _serializedObject = new SerializedObject(_workingInstance);

            _fieldsContainer.Clear();

            SerializedProperty prop = _serializedObject.GetIterator();
            bool enterChildren = true;
            while (prop.NextVisible(enterChildren))
            {
                enterChildren = false;
                if (ExcludedProperties.Contains(prop.name))
                    continue;

                _fieldsContainer.Add(new PropertyField(prop.Copy()));
            }

            _fieldsContainer.Bind(_serializedObject);
        }

        private System.Type GetSelectedType()
        {
            if (_weaponTypes == null || _weaponTypes.Count == 0)
                return null;

            int index = _weaponTypeField?.index ?? 0;
            if (index < 0 || index >= _weaponTypes.Count)
                return null;

            return _weaponTypes[index];
        }

        private void OnCreateClicked()
        {
            if (_workingInstance == null || _serializedObject == null)
            {
                EditorUtility.DisplayDialog("Error", "No weapon type selected.", "OK");
                return;
            }

            string weaponName = _weaponNameField.value?.Trim();
            if (string.IsNullOrEmpty(weaponName))
            {
                EditorUtility.DisplayDialog("Error", "Please enter a weapon name.", "OK");
                return;
            }

            string safeName = SanitizeFileName(weaponName);
            if (string.IsNullOrEmpty(safeName))
            {
                EditorUtility.DisplayDialog("Error", "Weapon name contains no valid filename characters.", "OK");
                return;
            }

            GameObject baseModel = _baseModelField.value as GameObject;
            if (baseModel == null)
            {
                EditorUtility.DisplayDialog("Error", "Please select a base model.", "OK");
                return;
            }

            System.Type selectedType = GetSelectedType();
            string typeFolderName = selectedType.Name.Replace("SO", "") + "s"; // e.g. SwordSO -> Swords

            // 1. Initialize folders.
            string dataPath = $"Assets/_Game/Data/Items/Weapons/{typeFolderName}";
            string prefabsPath = $"Assets/_Game/Prefabs/Items/Weapons/{typeFolderName}/{safeName}";

            Directory.CreateDirectory(dataPath);
            Directory.CreateDirectory(prefabsPath);
            AssetDatabase.Refresh();

            // 2. Persist the draft SO (it already carries the user's field edits via the bound inspector).
            _serializedObject.ApplyModifiedPropertiesWithoutUndo();
            _workingInstance.itemName = weaponName;

            string soPath = AssetDatabase.GenerateUniqueAssetPath($"{dataPath}/Weapon_{safeName}.asset");
            AssetDatabase.CreateAsset(_workingInstance, soPath);
            ItemSO weaponSO = _workingInstance;
            // Hand off ownership: the instance is now a persisted asset, not a disposable draft.
            _workingInstance = null;

            // 3. Create the equip-visual prefab (Drawn + Sheathed nodes).
            GameObject visualRoot = new GameObject($"{weaponName}_Visual");
            visualRoot.AddComponent<Rigidbody>().isKinematic = true;

            GameObject drawn = new GameObject("Drawn");
            drawn.transform.SetParent(visualRoot.transform);
            SetupModelChild(drawn, baseModel, true);

            GameObject sheathed = new GameObject("Sheathed");
            sheathed.transform.SetParent(visualRoot.transform);
            SetupModelChild(sheathed, baseModel, false);

            string visualPrefabPath = $"{prefabsPath}/{safeName}_Visual.prefab";
            GameObject visualPrefab = PrefabUtility.SaveAsPrefabAsset(visualRoot, visualPrefabPath);
            DestroyImmediate(visualRoot);

            // 4. Create the world (droppable / pickup) prefab.
            GameObject worldRoot = new GameObject($"{weaponName}_World");
            int interactableLayer = LayerMask.NameToLayer("Interactable");
            if (interactableLayer >= 0)
                worldRoot.layer = interactableLayer;
            else
                Debug.LogWarning("[WeaponCreator] 'Interactable' layer not found — world prefab left on Default layer.");

            var pickup = worldRoot.AddComponent<ItemPickup>();
            pickup.Configure(weaponSO);

            worldRoot.AddComponent<Rigidbody>();
            var worldCollider = worldRoot.AddComponent<BoxCollider>();
            Renderer modelRenderer = baseModel.GetComponentInChildren<Renderer>();
            if (modelRenderer != null)
            {
                worldCollider.center = modelRenderer.localBounds.center;
                worldCollider.size = modelRenderer.localBounds.size;
            }

            GameObject worldModel = new GameObject("Model");
            worldModel.transform.SetParent(worldRoot.transform);
            SetupModelChild(worldModel, baseModel, false);

            string worldPrefabPath = $"{prefabsPath}/{safeName}_World.prefab";
            GameObject worldPrefab = PrefabUtility.SaveAsPrefabAsset(worldRoot, worldPrefabPath);
            DestroyImmediate(worldRoot);

            // 5. Wire generated prefabs back onto the SO.
            weaponSO.worldItemPrefab = worldPrefab;
            if (weaponSO is EquipableItemSO equipable)
                equipable.equipVisualPrefab = visualPrefab;
            EditorUtility.SetDirty(weaponSO);
            AssetDatabase.SaveAssets();

            // 6. Generate the inventory icon from the world prefab preview.
            ItemIconGenerator.GenerateMissingIcons();

            Selection.activeObject = weaponSO;
            EditorGUIUtility.PingObject(weaponSO);
            EditorUtility.DisplayDialog("Success", $"Weapon '{weaponName}' created successfully!", "OK");

            // Reset the form with a fresh draft for the next weapon.
            _weaponNameField.SetValueWithoutNotify(string.Empty);
            RebuildFields();
        }

        private void SetupModelChild(GameObject parent, GameObject baseModel, bool isDrawn)
        {
            GameObject modelInstance = Instantiate(baseModel, parent.transform);
            modelInstance.name = "Mesh";

            if (isDrawn)
            {
                var trigger = parent.AddComponent<BoxCollider>();
                trigger.isTrigger = true;
                parent.AddComponent<WeaponHitbox>();
            }
        }

        private void DestroyWorkingInstanceIfUnsaved()
        {
            if (_workingInstance != null && !EditorUtility.IsPersistent(_workingInstance))
                DestroyImmediate(_workingInstance);
            _workingInstance = null;
        }

        private static string SanitizeFileName(string name)
        {
            foreach (char c in Path.GetInvalidFileNameChars())
                name = name.Replace(c, '_');
            return name.Trim();
        }
    }
}
